### ISSUE TITLE
Can't use build/crew/switch editor buttons after going to actions

### ISSUE THREAD

**Issue by Locusi** [linuxgurugamer/AGExt#6]
Hello!

I've got a problem described in title.
KSP Version: 1.7.0 with Making History Expansion on Windows 10
AGExt Version: 2.3.4
See the problem on 2nd screen:
1. Vanilla Action Groups:
![NormalAG](https://user-images.githubusercontent.com/23078545/56079829-e31bca80-5df9-11e9-873d-8e84547ace98.png)
2. AGExt:
![AGExt](https://user-images.githubusercontent.com/23078545/56079831-f333aa00-5df9-11e9-93b3-a5001fd6e64a.png)

Should I provide any more info?

Kind Regards,
Locusi

**Comment by Bavar1017** [comment]
Same problem here, without Making History Expansion

**Comment by linuxgurugamer** [comment]
Fixed in latest release

**Comment by Locusi** [comment]
Hello!

If latest release is 2.3.4 (as it says now) then it's not fixed, at least not in my case.

BTW, thanks for the awesome job you do on these mods.

EDIT: I've installed previous version (AGExt-2.3.3.8.zip) and saw that when I click Actions or Crew button all buttons turn off like on my second screen. Now, in version 2.3.4 Crew button works fine, but Actions still turns off all buttons. Maybe this will be helpful?

Kind Regards,
Locusi

**Comment by Squeech007** [comment]
Hi, i have the same issue as mentioned above for some time now... sadly. thx for your work on all those mods!!! /cheer

**Comment by linuxgurugamer** [comment]
This is a mostly unsupported mod, I'll take a look at it when I have some time

**Comment by xPROxSLASHERx** [comment]
I seem to be having the same issue as above on the latest version from CKAN (looks like same version as available here) where I cannot exit the action group menu as all tabs are greyed out.

**Comment by linuxgurugamer** [comment]
Log file would  be nice, also, would prefer support requests come in on the forum, not here

**Comment by linuxgurugamer** [comment]
There is a bug (soon to be fixed) in the initialization of the AGExt settings.  For now, you should see an AGExt button on the toolbar, click it once or twice to clear the issue.

**Comment by linuxgurugamer** [comment]
released
